// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv dotenv-expand
import dotenv from "dotenv";
import dotenvExpand from "dotenv-expand";
import { defineConfig } from "prisma/config";

// 환경 변수 로드 및 치환 ($VAR 형식 지원)
const env = dotenv.config();
dotenvExpand.expand(env);

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
