import { type RouteConfig, index, route, layout } from "@react-router/dev/routes";

export default [
    layout("routes/_app.tsx", [
        index("routes/home.tsx"),
        route("tweet/:tweetId", "routes/tweet.$tweetId.tsx"),
        route("user/:userId", "routes/user.$userId.tsx"),
        route("user/:userId/follows", "routes/user.$userId.follows.tsx"),
        route("profile", "routes/profile.tsx"),
        route("search", "routes/search.tsx"),
        route("bookmarks", "routes/bookmarks.tsx"),
        route("notifications", "routes/notifications.tsx"),
        route("travel-plans", "routes/travel-plans.tsx"),
        route("travel-plans/:id", "routes/travel-plans.$id.tsx"),
        route("tags/:slug", "routes/tags.$slug.tsx"),
    ]),
    route("api/auth/*", "routes/api.auth.ts", { id: "api-auth" }),
    route("api/tweets", "routes/api.tweets.ts"),
    route("api/likes", "routes/api.likes.ts"),
    route("api/retweets", "routes/api.retweets.ts"),
    route("api/bookmarks", "routes/api.bookmarks.ts"),
    route("api/bookmarks/collections", "routes/api.bookmarks.collections.ts"),
    route("api/notifications", "routes/api.notifications.ts"),
    route("api/follows", "routes/api.follows.ts"),
    route("api/upload", "routes/api.upload.ts"),
    route("api/users", "routes/api.users.ts"),
    route("api/tags", "routes/api.tags.ts"),
    route("api/travel-plans", "routes/api.travel-plans.ts"),
    route("api/travel-plans/:id", "routes/api.travel-plans.$id.ts"),
    route("api/travel-plan-items", "routes/api.travel-plan-items.ts"),
    route("api/travel-plan-items/:id", "routes/api.travel-plan-items.$id.ts"),
    route("api/ai-travel-log", "routes/api.ai-travel-log.ts"),
    route("auth/google/callback", "routes/api.auth.ts", { id: "google-callback" }),
    route("auth/kakao/callback", "routes/api.auth.ts", { id: "kakao-callback" }),
    route("login", "routes/login.tsx"),
    route("signup", "routes/signup.tsx"),
] satisfies RouteConfig;
